Mongo db
chingu-voyages/v45-tier3-team-42 pull request #17
Opened 2023-08-20 03:52 UTC by n3ndor

2023-08-20 05:33 UTC, paulpessoa requested changes
Good job Nandor, needs some tweaking but that's normal because of the version and approach conflict between Nextjs 12 and Nextjs13.

So we should use the `/app` directory, and instead of using `index.tsx` it will be `page.tsx`, these are some examples of files that need to be adjusted for the app to work again without errors.

@pierrelstan can you take a look?

![image](https://github.com/chingu-voyages/v45-tier3-team-42/assets/74559558/e5d797c0-9183-49ce-ba62-179fb95eb77d)

2023-08-20 05:33 UTC, paulpessoa commented on pages/api/addItem.ts
If you run `npm run lint` you will get some erros, just put this export way to solve it.

![image](https://github.com/chingu-voyages/v45-tier3-team-42/assets/74559558/fcc59fbd-b172-46f5-ab04-91f2b970d8ba)

2023-08-20 05:33 UTC, paulpessoa commented on tsconfig.json
> +<<<<<<< HEAD
duplicated variables

2023-08-20 05:33 UTC, paulpessoa commented on tsconfig.json
> +>>>>>>> e3839aae389c434edd5ed340d59b764cb99e834f
remove this comment

2023-08-20 05:33 UTC, paulpessoa commented on tailwind.config.js
should be a .ts file

2023-08-20 05:33 UTC, paulpessoa commented on styles/globals.css
review the folder structure

Next.js 13 use the /app directory and a diferent organization.

2023-08-20 05:33 UTC, paulpessoa commented on package.json
the package.json has some comments and duplicity.
set it like the file below, delete the package-lock.json and reinstall with `npm install`

```json
{
  "name": "chingu-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "cypress:open": "cypress open"
  },
  "dependencies": {
    "@types/node": "20.5.0",
    "@types/react": "18.2.20",
    "@types/react-dom": "18.2.7",
    "autoprefixer": "10.4.15",
    "eslint": "8.47.0",
    "eslint-config-next": "13.4.15",
    "mongodb": "^4.8.1",
    "next": "13.4.15",
    "postcss": "^8.4.28",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "tailwindcss": "^3.3.3"
  },
  "devDependencies": {
    "@types/node": "18.7.5",
    "@types/react": "16.9.17",
    "cypress": "^12.17.3",
    "typescript": "^4.6.3"
  }
}

```

2023-08-20 05:33 UTC, paulpessoa commented on package-lock.json
delete this file, and then run `npm install`

2023-08-20 05:33 UTC, paulpessoa commented on components/Nav.tsx
> +            <a href="/">Home</a>
We should use:

````js
import Link from "next/link";

 <Link href="/">Home</Link>
 
 ```

2023-08-20 05:33 UTC, paulpessoa commented on README.md
> +>>>>>>> e3839aae389c434edd5ed340d59b764cb99e834f
remove this line:

>>>>>>> e3839aae389c434edd5ed340d59b764cb99e834f

2023-08-20 05:33 UTC, paulpessoa commented on README.md
> +<<<<<<< HEAD
remove this line

2023-08-22 00:39 UTC, pierrelstan reviewed
There's an error that occurred when running 
`npm run build`

<img width="1312" alt="Screen Shot 2023-08-21 at 8 32 27 PM" src="https://github.com/chingu-voyages/v45-tier3-team-42/assets/23443242/a90d9b79-19ae-461b-9c13-183f556a28cb">

2023-08-22 00:48 UTC, n3ndor commented
I don't know why you get the build error, I tested before pushing:
![build](https://github.com/chingu-voyages/v45-tier3-team-42/assets/107216827/c02b7380-c6ef-4d71-9d42-e35ea4aaa337)

2023-08-24 21:01 UTC, paulpessoa approved these changes
lets move on

2023-08-24 21:02 UTC, merged